# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 21, 19, 29, 15, 192756, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 21, 19, 29, 22, 360259, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
