# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_auto_20151221_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlistitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bucketlistitem',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='bucketlistitem',
            name='bucket_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='bucketlist.BucketList'),
        ),
    ]
